; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266
board = d1_mini
framework = arduino
#upload_port = /dev/cu.usbserial-52870140141
#upload_port = /dev/cu.usbserial-52870161791
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit NeoPixel
	MFRC522
	OneWire
	DallasTemperature
	Adafruit MPR121@1.1.3
	bertmelis/espMqttClient@^1.7.2
	PubSubClient
	u8g2
	espSoftwareSerial
default_envs = module4

[env:ota-flash8266]
build_src_filter = 
	-<*>
	+<module02/task09-touch/main.cpp>

[env:ota-flash32]
build_src_filter = 
	-<*>
	+<module04/task07-node_a/>
lib_deps = 
	WiFi
upload_port = /dev/cu.usbserial-52870140141
platform = espressif32
board = mhetesp32minikit

[env:module4-a]
build_src_filter = 
	-<*>
	+<module04/task09-button/>
platform = espressif32
board = mhetesp32minikit
upload_protocol = espota
upload_port = esp32-minikitA.local
upload_flags = --auth=iotempower

[env:module4-b]
build_src_filter = 
	-<*>
	+<module04/task09-lights/>
platform = espressif32
board = mhetesp32minikit
upload_protocol = espota
upload_port = esp32-minikitB.local
upload_flags = --auth=iotempower
